/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as InboxRouteImport } from "./routes/_inbox";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as InboxIndexRouteImport } from "./routes/_inbox.index";
import { Route as InboxItemsIdRouteImport } from "./routes/_inbox.items.$id";

const InboxRoute = InboxRouteImport.update({
  id: "/_inbox",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => InboxRoute,
} as any);
const InboxItemsIdRoute = InboxItemsIdRouteImport.update({
  id: "/items/$id",
  path: "/items/$id",
  getParentRoute: () => InboxRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof InboxIndexRoute;
  "/login": typeof LoginRoute;
  "/settings": typeof SettingsRoute;
  "/items/$id": typeof InboxItemsIdRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/settings": typeof SettingsRoute;
  "/": typeof InboxIndexRoute;
  "/items/$id": typeof InboxItemsIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_inbox": typeof InboxRouteWithChildren;
  "/login": typeof LoginRoute;
  "/settings": typeof SettingsRoute;
  "/_inbox/": typeof InboxIndexRoute;
  "/_inbox/items/$id": typeof InboxItemsIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login" | "/settings" | "/items/$id";
  fileRoutesByTo: FileRoutesByTo;
  to: "/login" | "/settings" | "/" | "/items/$id";
  id:
    | "__root__"
    | "/_inbox"
    | "/login"
    | "/settings"
    | "/_inbox/"
    | "/_inbox/items/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  InboxRoute: typeof InboxRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  SettingsRoute: typeof SettingsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_inbox": {
      id: "/_inbox";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof InboxRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_inbox/": {
      id: "/_inbox/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof InboxIndexRouteImport;
      parentRoute: typeof InboxRoute;
    };
    "/_inbox/items/$id": {
      id: "/_inbox/items/$id";
      path: "/items/$id";
      fullPath: "/items/$id";
      preLoaderRoute: typeof InboxItemsIdRouteImport;
      parentRoute: typeof InboxRoute;
    };
  }
}

interface InboxRouteChildren {
  InboxIndexRoute: typeof InboxIndexRoute;
  InboxItemsIdRoute: typeof InboxItemsIdRoute;
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxIndexRoute: InboxIndexRoute,
  InboxItemsIdRoute: InboxItemsIdRoute,
};

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  InboxRoute: InboxRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
