/**
 * Writes packages/spec/vectors/receipts.json from fixed keys (ADR-016). Ed25519 signatures are
 * deterministic, so every value in the file is reproducible by any implementation from the inputs
 * alone — that is what makes it a test vector rather than an example. Run from packages/core:
 *
 *   npx tsx scripts/gen-receipt-vectors.ts
 *
 * The issuer key is RFC 8037 appendix A.1, the published Ed25519 test key; the agent key is
 * derived from the ASCII seed "surfingdog-inbox-agent-vector-01". Nothing here is a secret.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { ACK_TYP, ALG, b64u, RECEIPT_TYP, signReceipt, subjectHash, thumbprint } from "../src/receipts/sign";
import { createSecretBox } from "../src/secrets/box";

const enc = new TextEncoder();

const issuerPrivate = {
  kty: "OKP",
  crv: "Ed25519",
  x: "11qYAYKxCrfVS_7TyWQHOg7hcvPapiMlrwIaaPcHURo",
  d: "nWGxne_9WmC6hEr0kuwsxERJxWl7MmkZcDusAxyuf2A",
};

/** WebCrypto cannot import a private JWK without `x`, so a seed goes in as PKCS#8 and comes out as JWK. */
async function keyFromSeed(seed: Uint8Array) {
  const prefix = [0x30, 0x2e, 0x02, 0x01, 0x00, 0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x70, 0x04, 0x22, 0x04, 0x20];
  const pkcs8 = new Uint8Array([...prefix, ...seed]);
  const priv = await crypto.subtle.importKey("pkcs8", pkcs8, { name: "Ed25519" }, true, ["sign"]);
  const jwk = (await crypto.subtle.exportKey("jwk", priv)) as { x: string; d: string };
  return {
    privateJwk: { kty: "OKP", crv: "Ed25519", x: jwk.x, d: jwk.d },
    publicJwk: { kty: "OKP", crv: "Ed25519", x: jwk.x },
  };
}

async function sign(header: object, payload: object, privateJwk: object): Promise<string> {
  const input = `${b64u(enc.encode(JSON.stringify(header)))}.${b64u(enc.encode(JSON.stringify(payload)))}`;
  const key = await crypto.subtle.importKey(
    "jwk",
    { ...privateJwk, key_ops: ["sign"], ext: true },
    { name: "Ed25519" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign({ name: "Ed25519" }, key, enc.encode(input) as BufferSource);
  return `${input}.${b64u(new Uint8Array(sig))}`;
}

const issuerKid = await thumbprint(issuerPrivate);
// A JWKS entry carries its kid; a verifier that only has the key can also recompute it.
const issuer = {
  kid: issuerKid,
  publicJwk: { kty: "OKP", crv: "Ed25519", x: issuerPrivate.x, kid: issuerKid },
  privateJwk: issuerPrivate,
};
const agent = await keyFromSeed(enc.encode("surfingdog-inbox-agent-vector-01"));
const agentKid = await thumbprint(agent.publicJwk);
agent.publicJwk = { ...agent.publicJwk, kid: agentKid } as typeof agent.publicJwk;

const box = createSecretBox(["instance-a-secret"]);
if (!box) throw new Error("no box");
const sub = await subjectHash(await box.mac("receipt-subject"), "email:rita@example.com");

const confirmed = {
  iss: "https://inbox.example.com",
  sub,
  itm: "01M34AVYNXTNSE2RC495H3W8QS",
  typ: "booking",
  knd: "confirmed",
  iat: 1790000461,
  nonce: "0123456789abcdef0123456789abcdef",
  amt: { value: 4500, currency: "EUR" },
};
const paid = {
  iss: "https://inbox.example.com",
  sub,
  itm: "01M34B0B4ZQ9YQ3P7R6V1K2N3M",
  typ: "order",
  knd: "paid",
  iat: 1790000999,
  nonce: "fedcba9876543210fedcba9876543210",
  amt: { value: 2990, currency: "EUR" },
  pay: "card",
};
const receiptHeader = { alg: ALG, typ: RECEIPT_TYP, kid: issuerKid };
const jws1 = await signReceipt(confirmed as never, issuer as never);
const jws2 = await signReceipt(paid as never, issuer as never);

const ackHeader = { alg: ALG, typ: ACK_TYP, jwk: agent.publicJwk };
const ackPayload = { rcp: "01M34X9PAFXES35PXPY6QT944T", iat: 1790000500 };
const ack = await sign(ackHeader, ackPayload, agent.privateJwk);

const [h1, p1, s1] = jws1.split(".") as [string, string, string];
const tampered = `${h1}.${b64u(enc.encode(JSON.stringify({ ...confirmed, amt: { value: 1, currency: "EUR" } })))}.${s1}`;
const none = `${b64u(enc.encode(JSON.stringify({ alg: "none", typ: RECEIPT_TYP, kid: issuerKid })))}.${p1}.${s1}`;
const jwt = `${b64u(enc.encode(JSON.stringify({ alg: ALG, typ: "JWT", kid: issuerKid })))}.${p1}.${s1}`;
const foreign = await signReceipt(confirmed as never, { kid: agentKid, ...agent } as never);

const out = {
  $comment:
    "Test vectors for Surfing Dog Inbox receipts (ADR-016). Ed25519 is deterministic: re-signing `payload` with `issuer.private_jwk` reproduces `jws` byte for byte. Issuer key = RFC 8037 A.1; agent key seed = ASCII 'surfingdog-inbox-agent-vector-01'. Generated by packages/core/scripts/gen-receipt-vectors.ts. MIT.",
  spec: "surfingdog-inbox/0",
  issuer: { kid: issuerKid, public_jwk: issuer.publicJwk, private_jwk: issuerPrivate },
  agent: { kid: agentKid, public_jwk: agent.publicJwk, private_jwk: agent.privateJwk },
  subject: {
    $comment:
      "sub = base64url(HMAC-SHA-256(pepper, identity)) without padding; pepper = HKDF-SHA-256(ikm = utf8(secret), salt = empty, info = utf8('surfingdog-inbox/v1/mac/receipt-subject')) as a 256-bit HMAC key. Identity strings: 'email:<trimmed lowercased address>', else 'phone:<digits only>', else 'party:<party id>'.",
    secret: "instance-a-secret",
    identity: "email:rita@example.com",
    sub,
  },
  receipts: [
    { name: "booking confirmed, with an amount", header: receiptHeader, payload: confirmed, jws: jws1 },
    { name: "order paid by card", header: receiptHeader, payload: paid, jws: jws2 },
  ],
  acknowledgements: [
    {
      name: "valid, verified at its own iat",
      header: ackHeader,
      payload: ackPayload,
      jws: ack,
      verify_at: 1790000500,
      receipt_id: ackPayload.rcp,
    },
  ],
  refused_receipts: [
    { name: "payload changed after signing", jws: tampered, error: "bad_signature" },
    { name: "alg none", jws: none, error: "bad_alg" },
    { name: "typ JWT", jws: jwt, error: "bad_typ" },
    { name: "signed by a key the issuer never published", jws: foreign, error: "unknown_key" },
    { name: "not a JWS", jws: "not.a", error: "malformed" },
  ],
  refused_acknowledgements: [
    {
      name: "names another receipt",
      jws: await sign(ackHeader, { rcp: "01M34X9PAFXES35PXPY6QT9OTHER", iat: 1790000500 }, agent.privateJwk),
      verify_at: 1790000500,
      receipt_id: ackPayload.rcp,
      error: "bad_payload",
    },
    {
      name: "no jwk in the header",
      jws: await sign({ alg: ALG, typ: ACK_TYP }, ackPayload, agent.privateJwk),
      verify_at: 1790000500,
      receipt_id: ackPayload.rcp,
      error: "malformed",
    },
    {
      name: "two hours old",
      jws: await sign(ackHeader, { rcp: ackPayload.rcp, iat: 1790000500 - 7200 }, agent.privateJwk),
      verify_at: 1790000500,
      receipt_id: ackPayload.rcp,
      error: "expired",
    },
    {
      name: "dated ten minutes in the future",
      jws: ack,
      verify_at: 1790000500 - 600,
      receipt_id: ackPayload.rcp,
      error: "not_yet",
    },
  ],
};

const target = path.resolve(import.meta.dirname, "../../spec/vectors/receipts.json");
writeFileSync(target, `${JSON.stringify(out, null, 2)}\n`);
console.log(`wrote ${target}: issuer ${issuerKid}, agent ${agentKid}`);
