import {
  Archive,
  Ban,
  Banknote,
  Check,
  CheckCheck,
  ChevronRight,
  Clock,
  CreditCard,
  CreditCardX,
  FileText,
  type LucideIcon,
  MessageCircleQuestionMark,
  Package,
  PackageCheck,
  PackageX,
  Receipt,
  Reply,
  RotateCcw,
  ShieldCheck,
  ShieldOff,
  Truck,
  Undo2,
  UserX,
  X,
} from "lucide-react";

/** One icon per transition event, so the phone's action bar can be icons and still be understood. */
const ICONS: Record<string, LucideIcon> = {
  confirm: Check,
  accept: Check,
  approve: Check,
  propose: Clock,
  decline: X,
  reject: X,
  cancel: Ban,
  cancel_by_business: Ban,
  record_cancel: Ban,
  record_cancel_late: Ban,
  counter: Clock,
  retract: Undo2,
  propose_change: Clock,
  accept_change: Check,
  decline_change: X,
  retract_change: Undo2,
  request_info: MessageCircleQuestionMark,
  quote: FileText,
  record_payment: CreditCard,
  payment_failed: CreditCardX,
  charge_back: Undo2,
  record_charge_back: Undo2,
  refund: Banknote,
  withdraw: Undo2,
  record_withdrawal: Undo2,
  request_return: PackageX,
  open_return: PackageX,
  goods_back: PackageCheck,
  dispute_goods: X,
  record_delivery: Truck,
  request_payment: Receipt,
  start_fulfilment: Package,
  fulfil: PackageCheck,
  complete: CheckCheck,
  no_show: UserX,
  close: Archive,
  mark_spam: ShieldOff,
  unspam: ShieldCheck,
  reopen: RotateCcw,
  answer: Reply,
};

export function EventIcon({ event, className = "icon" }: { event: string; className?: string | undefined }) {
  const Icon = ICONS[event] ?? ChevronRight;
  return <Icon className={className} aria-hidden="true" />;
}
